# Generated by Django 6.0.1 on 2026-01-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="fps",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="resolution",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="videos/thumbnails/"
            ),
        ),
    ]
