# Generated by Django 5.2 on 2026-02-02 04:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_video_fps_video_resolution_video_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(
                upload_to="videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "avi", "mov", "mkv"]
                    )
                ],
            ),
        ),
    ]
