# Generated by Django 5.2 on 2026-02-02 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "detection",
            "0002_alter_detection_id_alter_detectionsnapshot_detection_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="detection",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="detectionsnapshot",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="detection",
            name="video_timestamp",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="detectionsnapshot",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 2, 2, 4, 41, 40, 732437, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="detectionsnapshot",
            name="video_timestamp",
            field=models.DurationField(null=True),
        ),
    ]
