# Generated by Django 5.2 on 2026-02-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmland", "0002_alter_farmland_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmland",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farmland",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
